// ── TableauEvaluator ── XML-based grading engine for Tableau VL
class TableauEvaluator {
  constructor(checks, onResultUpdate) {
    this.checks = checks;
    this.onResultUpdate = onResultUpdate;
    this.totalScore = 0;
    this.maxScore = checks.reduce((s, c) => s + c.marks, 0);
    this.lastResults = [];
    this.labId = null;
    this.labTitle = '';
  }

  async processFile(file) {
    try {
      let xmlString = '';
      if (file.name.endsWith('.twbx')) {
        if (typeof JSZip === 'undefined') throw new Error('JSZip not loaded.');
        const zip = await new JSZip().loadAsync(file);
        const twbName = Object.keys(zip.files).find(n => n.endsWith('.twb'));
        if (!twbName) throw new Error('No .twb found inside .twbx archive.');
        xmlString = await zip.files[twbName].async('string');
      } else if (file.name.endsWith('.twb')) {
        xmlString = await file.text();
      } else {
        throw new Error('Please upload a .twb or .twbx file.');
      }
      const parser = new DOMParser();
      const xml = parser.parseFromString(xmlString, 'text/xml');
      if (xml.getElementsByTagName('parsererror').length > 0)
        throw new Error('XML parse error in workbook.');
      this.runChecks(xml);
    } catch (e) {
      console.error(e);
      const errEl = document.getElementById('eval-error');
      if (errEl) { errEl.textContent = '⚠ ' + e.message; errEl.style.display = 'block'; }
      else alert('Evaluation Error: ' + e.message);
    }
  }

  runChecks(xml) {
    this.totalScore = 0;
    const results = [];
    this.checks.forEach(c => {
      let passed = false;
      try { passed = c.evalFn(xml); } catch(e) { console.error(c.id, e); }
      if (passed) this.totalScore += c.marks;
      results.push({ id: c.id, name: c.name, marks: passed ? c.marks : 0, maxMarks: c.marks, passed });
    });
    this.lastResults = results;
    if (this.onResultUpdate) this.onResultUpdate(results, this.totalScore, this.maxScore);
  }

  exportReport(labTitle) {
    const rows = this.lastResults.map(r =>
      `| ${r.name} | ${r.passed ? '✅ Pass' : '❌ Fail'} | ${r.marks}/${r.maxMarks} |`
    ).join('\n');
    const pct = Math.round((this.totalScore / this.maxScore) * 100);
    const grade = pct >= 90 ? 'A' : pct >= 75 ? 'B' : pct >= 60 ? 'C' : 'F';
    const md = `# Tableau VL — Evaluation Report
**Lab:** ${labTitle || document.title}
**Date:** ${new Date().toLocaleString()}
**Score:** ${this.totalScore} / ${this.maxScore} (${pct}%) — Grade: **${grade}**

## Check Results
| Check | Status | Marks |
|---|---|---|
${rows}

---
*Generated by Tableau Virtual Laboratory XML Evaluator*`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `tableau_vl_report_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  // ── Static XML Helpers ──
  static findNodes(xml, tagName) {
    // Try standard search first, then namespace-agnostic search
    let nodes = xml.getElementsByTagName(tagName);
    if (nodes.length === 0) {
      nodes = xml.getElementsByTagNameNS('*', tagName);
    }
    return nodes;
  }

  static hasDatasource(xml, sub) {
    const ds = this.findNodes(xml, 'datasource');
    for (let i = 0; i < ds.length; i++) {
      const n = (ds[i].getAttribute('name') || '') + (ds[i].getAttribute('caption') || '');
      if (n.toLowerCase().includes(sub.toLowerCase())) return true;
    }
    return false;
  }
  static hasRenamedField(xml, caption) {
    const cols = this.findNodes(xml, 'column');
    for (let i = 0; i < cols.length; i++)
      if ((cols[i].getAttribute('caption') || '').toLowerCase() === caption.toLowerCase()) return true;
    return false;
  }
  static hasDatatypeChange(xml, fieldName, dtype) {
    const cols = this.findNodes(xml, 'column');
    for (let i = 0; i < cols.length; i++) {
      const n = cols[i].getAttribute('name') || '';
      if (n.toLowerCase().includes(fieldName.toLowerCase()) && cols[i].getAttribute('datatype') === dtype) return true;
    }
    return false;
  }
  static hasMarkType(xml, cls) {
    const marks = this.findNodes(xml, 'mark');
    for (let i = 0; i < marks.length; i++) {
      const markClass = (marks[i].getAttribute('class') || '').toLowerCase();
      if (markClass === cls.toLowerCase()) return true;
    }
    return false;
  }
  static hasFormulaKeyword(xml, ...keywords) {
    const calcs = this.findNodes(xml, 'calculation');
    for (let i = 0; i < calcs.length; i++) {
      const f = (calcs[i].getAttribute('formula') || '').toUpperCase();
      if (keywords.every(k => f.includes(k.toUpperCase()))) return true;
    }
    return false;
  }
  static hasParameter(xml) {
    const cols = this.findNodes(xml, 'column');
    for (let i = 0; i < cols.length; i++)
      if (cols[i].hasAttribute('param-domain-type')) return true;
    return false;
  }
  static worksheetCount(xml) {
    return this.findNodes(xml, 'worksheet').length;
  }
  static dashboardCount(xml) {
    return this.findNodes(xml, 'dashboard').length;
  }
  static hasDashboardZones(xml, minZones) {
    const dashes = this.findNodes(xml, 'dashboard');
    for (let i = 0; i < dashes.length; i++) {
      let ws = 0;
      const zones = dashes[i].getElementsByTagName('zone'); // zones are inside dashboard
      for (let j = 0; j < zones.length; j++)
        if (zones[j].getAttribute('type-v2') === 'worksheet') ws++;
      if (ws >= minZones) return true;
    }
    return false;
  }
  static hasTextObject(xml) {
    const zones = this.findNodes(xml, 'zone');
    for (let i = 0; i < zones.length; i++)
      if (zones[i].getAttribute('type-v2') === 'text') return true;
    return false;
  }
  static hasNode(xml, tagName) {
    if (this.findNodes(xml, tagName).length > 0) return true;
    // Fallback for labels which are often 'mark-labels' in Tableau
    if (tagName.toLowerCase() === 'label') {
       if (this.findNodes(xml, 'mark-labels').length > 0) return true;
       if (this.findNodes(xml, 'mark-label').length > 0) return true;
    }
    return false;
  }
  static hasConnectionType(xml, cls) {
    const conns = xml.getElementsByTagName('connection');
    for (let i = 0; i < conns.length; i++)
      if ((conns[i].getAttribute('class') || '').includes(cls)) return true;
    return false;
  }
  static hasDrillPath(xml, minLevels) {
    const dp = xml.getElementsByTagName('drill-path');
    for (let i = 0; i < dp.length; i++)
      if (dp[i].getElementsByTagName('field').length >= minLevels) return true;
    return false;
  }
}

// ── Upload Zone Setup ──
function setupUploadZone(zoneId, inputId, evaluator) {
  const zone = document.getElementById(zoneId);
  const input = document.getElementById(inputId);
  if (!zone || !input) return;

  const process = file => {
    const label = document.getElementById('file-label');
    if (label) label.textContent = '📄 ' + file.name;
    zone.classList.add('loaded');
    evaluator.processFile(file);
  };

  zone.addEventListener('click', () => input.click());
  zone.addEventListener('dragover', e => { e.preventDefault(); zone.classList.add('dragover'); });
  zone.addEventListener('dragleave', () => zone.classList.remove('dragover'));
  zone.addEventListener('drop', e => {
    e.preventDefault(); zone.classList.remove('dragover');
    if (e.dataTransfer.files[0]) process(e.dataTransfer.files[0]);
  });
  input.addEventListener('change', e => { if (e.target.files[0]) process(e.target.files[0]); });
}

// ── Toast ──
function showToast(msg, type = 'success') {
  let toast = document.getElementById('toast');
  if (!toast) { toast = document.createElement('div'); toast.id = 'toast'; document.body.appendChild(toast); }
  toast.textContent = msg;
  toast.className = 'toast show ' + type;
  clearTimeout(toast._t);
  toast._t = setTimeout(() => toast.classList.remove('show'), 2800);
}

// JSON Progress Backup/Restore (called from index.html)
function backupAllProgress() {
  var data = {};
  for (var i = 0; i < localStorage.length; i++) {
    var k = localStorage.key(i);
    if (k && k.startsWith('tvl_')) data[k] = localStorage.getItem(k);
  }
  var blob = new Blob([JSON.stringify(data, null, 2)], {type:'application/json'});
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'tableau_vl_backup_' + new Date().toISOString().slice(0,10) + '.json';
  a.click(); URL.revokeObjectURL(a.href);
}
function restoreFromJSON(file) {
  var r = new FileReader();
  r.onload = function(e) {
    try {
      var data = JSON.parse(e.target.result); var n = 0;
      Object.keys(data).forEach(function(k) { if (k.startsWith('tvl_')) { localStorage.setItem(k, data[k]); n++; } });
      alert('Restored ' + n + ' records. Page will reload.'); location.reload();
    } catch(ex) { alert('Invalid backup file.'); }
  };
  r.readAsText(file);
}
