// ── TableauEvaluator ── XML-based grading engine for Tableau VL
// Safe localStorage wrapper to prevent QuotaExceededError crashes
const originalSetItem = localStorage.setItem;
localStorage.setItem = function(key, value) {
  try {
    originalSetItem.apply(this, arguments);
  } catch(e) {
    if (e.name === 'QuotaExceededError' || e.name === 'NS_ERROR_DOM_QUOTA_REACHED') {
      const errEl = document.getElementById('eval-error');
      if (errEl) {
        errEl.textContent = '⚠ Storage quota exceeded! Cannot save progress or screenshots. Please clear some previous labs.';
        errEl.style.display = 'block';
      }
      console.error('localStorage quota exceeded', e);
    }
  }
};

class TableauEvaluator {
  constructor(checks, onResultUpdate) {
    this.checks = checks;
    this.onResultUpdate = onResultUpdate;
    this.totalScore = 0;
    this.maxScore = checks.reduce((s, c) => s + c.marks, 0);
    this.lastResults = [];
    this.labId = null;
    this.labTitle = '';
  }

  async processFile(file) {
    try {
      let xmlString = '';
      if (file.name.endsWith('.twbx')) {
        if (typeof JSZip === 'undefined') throw new Error('JSZip not loaded.');
        const zip = await new JSZip().loadAsync(file);
        const twbName = Object.keys(zip.files).find(n => n.endsWith('.twb'));
        if (!twbName) throw new Error('No .twb found inside .twbx archive.');
        xmlString = await zip.files[twbName].async('string');
      } else if (file.name.endsWith('.twb')) {
        xmlString = await file.text();
      } else {
        throw new Error('Please upload a .twb or .twbx file.');
      }
      const parser = new DOMParser();
      const xml = parser.parseFromString(xmlString, 'text/xml');
      if (xml.getElementsByTagName('parsererror').length > 0)
        throw new Error('XML parse error in workbook.');
      this.runChecks(xml, xmlString);
    } catch (e) {
      console.error(e);
      const errEl = document.getElementById('eval-error');
      if (errEl) { errEl.textContent = '⚠ ' + e.message; errEl.style.display = 'block'; }
      else alert('Evaluation Error: ' + e.message);
    }
  }

  runChecks(xml, xmlString) {
    this.totalScore = 0;
    const results = [];
    this.checks.forEach(c => {
      let passed = false;
      try { passed = c.evalFn(xml, xmlString); } catch(e) { console.error(c.id, e); }
      if (passed) this.totalScore += c.marks;
      results.push({ id: c.id, name: c.name, marks: passed ? c.marks : 0, maxMarks: c.marks, passed });
    });
    this.lastResults = results;
    if (this.onResultUpdate) this.onResultUpdate(results, this.totalScore, this.maxScore);
  }

  exportReport(labTitle) {
    const rows = this.lastResults.map(r =>
      `| ${r.name} | ${r.passed ? '✅ Pass' : '❌ Fail'} | ${r.marks}/${r.maxMarks} |`
    ).join('\n');
    const pct = Math.round((this.totalScore / this.maxScore) * 100);
    const grade = pct >= 90 ? 'A' : pct >= 75 ? 'B' : pct >= 60 ? 'C' : 'F';
    const md = `# Tableau VL — Evaluation Report
**Lab:** ${labTitle || document.title}
**Date:** ${new Date().toLocaleString()}
**Score:** ${this.totalScore} / ${this.maxScore} (${pct}%) — Grade: **${grade}**

## Check Results
| Check | Status | Marks |
|---|---|---|
${rows}

---
*Generated by Tableau Virtual Laboratory XML Evaluator*`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `tableau_vl_report_${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  // ── Static XML Helpers ──
  static findNodes(xml, tagName) {
    // Always use namespace-agnostic search for maximum reliability
    return Array.from(xml.getElementsByTagNameNS('*', tagName));
  }

  static hasDatasource(xml, sub) {
    const ds = this.findNodes(xml, 'datasource');
    for (let i = 0; i < ds.length; i++) {
      const n = (ds[i].getAttribute('name') || '') + (ds[i].getAttribute('caption') || '');
      if (n.toLowerCase().includes(sub.toLowerCase())) return true;
    }
    return false;
  }
  static hasRenamedField(xml, caption) {
    const cols = this.findNodes(xml, 'column');
    for (let i = 0; i < cols.length; i++)
      if ((cols[i].getAttribute('caption') || '').toLowerCase() === caption.toLowerCase()) return true;
    return false;
  }
  static hasDatatypeChange(xml, fieldName, dtype) {
    const cols = this.findNodes(xml, 'column');
    for (let i = 0; i < cols.length; i++) {
      const n = cols[i].getAttribute('name') || '';
      if (n.toLowerCase().includes(fieldName.toLowerCase()) && cols[i].getAttribute('datatype') === dtype) return true;
    }
    return false;
  }

  static hasMarkType(xml, cls, xmlString) {
    const target = cls.toLowerCase();
    const content = (xmlString || new XMLSerializer().serializeToString(xml)).toLowerCase();
    
    // Split into individual worksheet blocks
    const sheets = content.split('<worksheet');
    
    for (let s of sheets) {
      // Extract the <cols> and <rows> shelf text — this is the definitive encoding
      const colsMatch = s.match(/<cols>([^<]*)<\/cols>/);
      const rowsMatch = s.match(/<rows>([^<]*)<\/rows>/);
      const cols = colsMatch ? colsMatch[1] : '';
      const rows = rowsMatch ? rowsMatch[1] : '';
      
      // BAR CHART: dimension (none:) on cols + measure (sum:sales) on rows
      // OR: dimension (none:) on rows + measure (sum:sales) on cols (transposed)
      if (target === 'bar') {
        const barCheck = 
          (cols.includes('none:category') || cols.includes('none:sub-category') || cols.includes('none:region') || cols.includes('none:segment'))
          && (rows.includes('sum:sales') || rows.includes('sum:profit') || rows.includes('sum:quantity'))
          || (rows.includes('none:category') || rows.includes('none:sub-category'))
          && (cols.includes('sum:sales') || cols.includes('sum:profit'));
        if (barCheck) return true;
      }
      
      // LINE CHART: date field on cols (mn: = month, yr: = year, qr: = quarter, dy: = day)
      if (target === 'line') {
        const lineCheck = 
          (cols.includes('mn:order date') || cols.includes('yr:order date') || cols.includes('qr:order date') || cols.includes('dy:order date') || cols.includes(':order date'))
          && (rows.includes('sum:profit') || rows.includes('sum:sales'));
        if (lineCheck) return true;
      }
      
      // SCATTER PLOT: both axes are measures (sum:)
      if (target === 'circle' || target === 'scatter') {
        const scatterCheck = 
          (cols.includes('sum:sales') && rows.includes('sum:profit'))
          || (cols.includes('sum:profit') && rows.includes('sum:sales'));
        if (scatterCheck) return true;
      }
    }
    
    // Fallback: broad content search
    if (target === 'bar') return content.includes('none:category') && content.includes('sum:sales');
    if (target === 'line') return content.includes(':order date') && content.includes('sum:profit');
    if (target === 'circle' || target === 'scatter') return content.includes('sum:sales') && content.includes('sum:profit');
    if (target === 'map') return content.includes('filled-map') || content.includes("mark-type' value='map'") || content.includes('maptype');
    if (target === 'square') return content.includes("mark-type' value='square'") || content.includes('<mark type="square"') || content.includes("type='square'");
    return false;
  }

  static hasFormulaKeyword(xml, ...keywords) {
    const calcs = this.findNodes(xml, 'calculation');
    for (let i = 0; i < calcs.length; i++) {
      const f = (calcs[i].getAttribute('formula') || '').toUpperCase();
      if (keywords.every(k => f.includes(k.toUpperCase()))) return true;
    }
    return false;
  }
  static hasParameter(xml) {
    const cols = this.findNodes(xml, 'column');
    for (let i = 0; i < cols.length; i++)
      if (cols[i].hasAttribute('param-domain-type')) return true;
    return false;
  }
  static worksheetCount(xml) {
    return this.findNodes(xml, 'worksheet').length;
  }
  static dashboardCount(xml) {
    return this.findNodes(xml, 'dashboard').length;
  }
  static hasDashboardZones(xml, minZones) {
    const dashes = this.findNodes(xml, 'dashboard');
    for (let i = 0; i < dashes.length; i++) {
      let ws = 0;
      const zones = dashes[i].getElementsByTagNameNS('*', 'zone');
      for (let j = 0; j < zones.length; j++)
        if (zones[j].getAttribute('type-v2') === 'worksheet') ws++;
      if (ws >= minZones) return true;
    }
    return false;
  }
  static hasTextObject(xml) {
    const zones = this.findNodes(xml, 'zone');
    for (let i = 0; i < zones.length; i++)
      if (zones[i].getAttribute('type-v2') === 'text') return true;
    return false;
  }
  static hasNode(xml, tagName, xmlString) {
    const target = tagName.toLowerCase();
    const content = (xmlString || new XMLSerializer().serializeToString(xml)).toLowerCase();
    
    if (target === 'label' || target === 'mark-labels') {
      // Tableau writes: attr='mark-labels-show' value='true'
      return content.includes("mark-labels-show' value='true'") ||
             content.includes('mark-labels-show" value="true"') ||
             content.includes('mark-labels-show') ||
             content.includes('labels-cull');
    }
    if (target === 'color') {
       return content.includes('mark-color') || content.includes('<color') || content.includes("encoding='color'");
    }
    return this.findNodes(xml, target).length > 0 || content.includes('<' + target);
  }
  static hasConnectionType(xml, cls) {
    const conns = xml.getElementsByTagName('connection');
    for (let i = 0; i < conns.length; i++)
      if ((conns[i].getAttribute('class') || '').includes(cls)) return true;
    return false;
  }
  static hasDrillPath(xml, minLevels) {
    const dp = xml.getElementsByTagName('drill-path');
    for (let i = 0; i < dp.length; i++)
      if (dp[i].getElementsByTagName('field').length >= minLevels) return true;
    return false;
  }
}

// ── Upload Zone Setup ──
function setupUploadZone(zoneId, inputId, evaluator) {
  const zone = document.getElementById(zoneId);
  const input = document.getElementById(inputId);
  if (!zone || !input) return;

  const process = file => {
    const label = document.getElementById('file-label');
    if (label) label.textContent = '📄 ' + file.name;
    zone.classList.add('loaded');
    evaluator.processFile(file);
  };

  zone.addEventListener('click', () => input.click());
  zone.addEventListener('dragover', e => { e.preventDefault(); zone.classList.add('dragover'); });
  zone.addEventListener('dragleave', () => zone.classList.remove('dragover'));
  zone.addEventListener('drop', e => {
    e.preventDefault(); zone.classList.remove('dragover');
    if (e.dataTransfer.files[0]) process(e.dataTransfer.files[0]);
  });
  input.addEventListener('change', e => { if (e.target.files[0]) process(e.target.files[0]); });
}

// ── Toast ──
function showToast(msg, type = 'success') {
  let toast = document.getElementById('toast');
  if (!toast) { toast = document.createElement('div'); toast.id = 'toast'; document.body.appendChild(toast); }
  toast.textContent = msg;
  toast.className = 'toast show ' + type;
  clearTimeout(toast._t);
  toast._t = setTimeout(() => toast.classList.remove('show'), 2800);
}

// JSON Progress Backup/Restore (called from index.html)
function backupAllProgress() {
  var data = {};
  for (var i = 0; i < localStorage.length; i++) {
    var k = localStorage.key(i);
    if (k && k.startsWith('tvl_')) data[k] = localStorage.getItem(k);
  }
  var blob = new Blob([JSON.stringify(data, null, 2)], {type:'application/json'});
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'tableau_vl_backup_' + new Date().toISOString().slice(0,10) + '.json';
  a.click(); URL.revokeObjectURL(a.href);
}
function restoreFromJSON(file) {
  var r = new FileReader();
  r.onload = function(e) {
    try {
      var data = JSON.parse(e.target.result); var n = 0;
      Object.keys(data).forEach(function(k) { if (k.startsWith('tvl_')) { localStorage.setItem(k, data[k]); n++; } });
      alert('Restored ' + n + ' records. Page will reload.'); location.reload();
    } catch(ex) { alert('Invalid backup file.'); }
  };
  r.readAsText(file);
}
